development:
  dialect: postgres
  datasource: ${DB_CONNECTION_STRING}
  dir: migrations

production:
  dialect: postgres
  datasource: ${DB_CONNECTION_STRING}
  dir: migrations
  table: migrations

# Создать файл миграции
# sql-migrate new up

# Откатить миграцию на шаг назад
# sql-migrate down