basePath: /
definitions:
  models.SongDetail:
    properties:
      link:
        type: string
      releaseDate:
        type: string
      text:
        type: string
    type: object
  models.Songs:
    properties:
      ID:
        type: integer
      detail:
        $ref: '#/definitions/models.SongDetail'
      group:
        type: string
      song:
        type: string
    type: object
host: localhost:8586
info:
  contact:
    email: zatrasz@ya.ru
    name: Михаил Токмачев
    url: https://t.me/Zatrasz
  title: Реализация онлайн библиотеки песен
  version: "1.0"
paths:
  /songs:
    get:
      consumes:
      - application/json
      description: Принимает поля group , song , releaseDate , text , link .
      parameters:
      - description: Фильтр по названию
        in: query
        name: filter
        type: string
      - default: 10
        description: Количество записей на странице для пагинации
        in: query
        name: limit
        type: integer
      - default: 1
        description: Номер страницы
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Список песен
          schema:
            items:
              $ref: '#/definitions/models.Songs'
            type: array
        "400":
          description: Недопустимый параметр смещения
          schema:
            type: string
        "500":
          description: Ошибка при получение списка песен или Ошибка при обработке
            запроса
          schema:
            type: string
      summary: Получение данных с фильтрацией по всем полям и пагинацией
      tags:
      - Songs
    post:
      consumes:
      - application/json
      description: Принимает обязательные поля group , song .
      parameters:
      - description: Данные структуры песни
        in: body
        name: songs
        required: true
        schema:
          $ref: '#/definitions/models.Songs'
      produces:
      - application/json
      responses:
        "200":
          description: Успешно созданная запись < Ok >
          schema:
            type: string
        "400":
          description: Неверный формат запроса или не верно заполнены обязательные
            поля
          schema:
            type: string
        "500":
          description: Не получены детальные данные из API или ошибка при сохранении
            в бд
          schema:
            type: string
      summary: Добавление новой песни
      tags:
      - Songs
swagger: "2.0"
